# Generated by Django 4.1.1 on 2022-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userr', models.CharField(max_length=200, null=True, verbose_name='First name')),
                ('items', models.CharField(max_length=200, null=True, verbose_name='Middle name')),
                ('quantity', models.CharField(max_length=200, null=True, verbose_name='Last name')),
                ('totalpoints', models.CharField(max_length=200, null=True, verbose_name='Employee Number')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
